### ISSUE TITLE
Cannot install package

### ISSUE THREAD

**Issue by gdyrrahitis** [Syrx/Syrx.Npgsql#1]
Cannot install nuget package due to following error.

Error message:

```
Error: Unable to resolve dependency 'Syrx.Connectors.Databases.Npgsql'.
Source(s) used: 'nuget.org', 'CliFallbackFolder', 'Microsoft Visual Studio Offline Packages'
```

Onto it...

**Comment by sextondjc** [comment]
Looks like I forgot to upload the package to nuget. Will do that shortly. 

Will also start altering the solution layouts like we discussed.

**Comment by sextondjc** [comment]
[Fixed](https://www.nuget.org/packages/Syrx.Connectors.Databases.Npgsql).
